VSSS-INF: Robots Class Reference
Robots Class Reference
#include <robots.hpp>
Data Structures
struct _Status
A structure to communicate Robot's Status.
struct Command
A structure to encapsulate and communicate Robot commands.
struct Robot
Public Types
enum CMD { POSITION, SPEED, ORIENTATION, VECTOR }
Static Public Member Functions
static std::vector< Command > get_commands ()
GETTERS.
static char get_ID (int robot)
static bool get_usingPotField (int robot)
static cv::Point get_position (int robot)
static cv::Point get_target (int robot)
static double get_orientation (int robot)
static cv::Point get_secondary_tag (int robot)
static bool get_fixedPos (int robot)
static CMD get_cmdType (int robot)
static float get_velocity (int robot)
static float get_default_velocity (int robot)
static float get_default_role_velocity (int role)
static int get_role (int robot)
static int get_status (int robot)
static double get_transAngle (int robot)
static void set_ID (int robot, char ID)
SETTERS.
static void set_position (int robot, cv::Point position)
static void set_orientation (int robot, double orientation)
static void set_secondary_tag (int robot, cv::Point secondary)
static void set_cmdType (int robot, CMD cmdType)
static void set_fixedPos (int robot, bool fixedPos)
static void set_usingPotField (int robot, bool usingPotField)
static void set_velocity (int robot, int role)
static void set_velocity (int robot, float velocity)
static void set_velocity (int robot)
static void set_default_velocity (int robot, float vel)
static void set_default_role_velocity (int role, float vel)
static void set_status (int robot, int status)
static void set_role (int robot, int role)
static void set_transAngle (int robot, double transAngle)
static void set_target (int robot, cv::Point target)
static void set_command (int robot, cv::Point target, float vel=-1)
static void set_command (int robot, float Vl, float Vr)
static void set_command (int robot, double theta, float vel=-1)
static void reset_targets ()
static void reset_commands ()
static bool is_posistion_set (int robot)
static bool is_target_set (int robot)
static void stop (int robot)
static void spin_clockwise (int robot, float vel=-1)
static void spin_counter_clockwise (int robot, float vel=-1)
static void look_at (int robot, double orientation, float vel=-1)
static void look_at (int robot, cv::Point target, float vel=-1)
static void kick (int robot, cv::Point target)
Static Public Attributes
static const int SIZE = 3
The number of robots. Can be used by all classes statically or dynamically.
static constexpr float MAX_VEL = 1.4f
Robot's physical maximum velocity in meters/second. Can be used by all classes statically or dynamically.
Private Member Functions
Robots ()
Initializes our arrays.
Static Private Member Functions
static Robots * get_instance ()
static bool _check_index (const std::string &caller, int i)
Private Attributes
std::vector< Robot > list
A list of N robots. Must be unique in the entire program.
float default_vel [3]
The default velocities for each role (GK, DEF or ATK)
Static Private Attributes
static Robots * instance = nullptr
The unique instance of this class.
Detailed Description
Definition at line 17 of file robots.hpp.
Member Enumeration Documentation
CMD
enum Robots::CMD
All available types of command that can be sent to robot. This refers to robot's intrinsics and must be encapsulated inside the robot's class.
Enumerator
POSITION
SPEED
ORIENTATION
VECTOR
Definition at line 31 of file robots.hpp.
               {
         POSITION,
         SPEED,
         ORIENTATION,
         VECTOR
     };
Constructor & Destructor Documentation
Robots()
Robots::Robots () private
Initializes our arrays.
Definition at line 16 of file robots.cpp.
References default_vel, list, and N_ROBOTS.
Referenced by get_instance().
                {
     list.resize(N_ROBOTS);
     for(float & v : default_vel) v = 0.8;
     // Inicialização automática dos valores corretos para os robôs que usamos. Não é crucial pro funcionamento.
     // goleiro
     list.at(0).ID = 'C';
     default_vel[0] = 0.6; // mais precisão
     list.at(0).role = 0;
     // defensor
     list.at(1).ID = 'F';
     default_vel[1] = 0.8; // balanceado
     list.at(1).role = 1;
     // atacante
     list.at(2).ID = 'G';
     default_vel[2] = 1.0; // mais agilidade
     list.at(2).role = 2;
 }
Member Function Documentation
_check_index()
bool Robots::_check_index (const std::string & caller, int i) static private
Checks if a given index is valid considering the number of robots. !TODO convert all indexes to an unsigned type
Parameters
caller The name of the method that called Robot::_check_index. This is set automatically by #define directives.
i An index to validate.
Returns
True if 'i' is valid, False otherwise.
Definition at line 35 of file robots.cpp.
References debug_error, and N_ROBOTS.
{
     if(i > N_ROBOTS || i < 0) {
         debug_error("[" + caller + "] Index out of range: " + to_string(i));
         return false;
     }
     return true;
 }
get_cmdType()
Robots::CMD Robots::get_cmdType (int robot) static
Gets the command type of a given robot.
Parameters
robot Robot's index.
Returns
An enum CMD value.
Definition at line 100 of file robots.cpp.
References check_index, get_instance(), list, and POSITION.
Referenced by Strategy::fixed_position_check(), and Strategy::position_to_vector().
{
     if(!check_index(robot)) return CMD::POSITION;
     return get_instance()->list.at(robot).cmdType;
 }
get_commands()
std::vector< Robots::Command > Robots::get_commands () static
GETTERS.
Encapsulate robots' commands and status to send via Communication. !TODO see if there is any kind of desynchronization when this is encapsulating robot data and Vision is updating our position, for example.
Returns
An array of Commands, one for each robot.
Definition at line 43 of file robots.cpp.
References get_instance(), list, N_ROBOTS, ORIENTATION, POSITION, SPEED, and VECTOR.
Referenced by CamCap::send_cmd_thread().
{
     std::vector<Command> res;
     res.resize(N_ROBOTS);
     for(unsigned short i = 0; i < N_ROBOTS; i++) {
         res.at(i).ID = get_instance()->list.at(i).ID;
         res.at(i).cmdType = get_instance()->list.at(i).cmdType;
         res.at(i).Status.position = get_instance()->list.at(i).position;
         res.at(i).Status.orientation = get_instance()->list.at(i).orientation;
         res.at(i).Status.vmax = get_instance()->list.at(i).vmax;
         switch(res.at(i).cmdType) {
             case CMD::POSITION:
                 res.at(i).Msg.target = get_instance()->list.at(i).target;
                 break;
             case CMD::SPEED:
                 res.at(i).Msg.Velocity.left = get_instance()->list.at(i).Vl;
                 res.at(i).Msg.Velocity.right = get_instance()->list.at(i).Vr;
                 break;
             case CMD::ORIENTATION:
                 res.at(i).Msg.theta = get_instance()->list.at(i).targetOrientation;
                 break;
             case CMD::VECTOR:
                 res.at(i).Msg.theta = get_instance()->list.at(i).transAngle;
                 break;
             default: break;
         }
     }
     return res;
 }
get_default_role_velocity()
float Robots::get_default_role_velocity (int role) static
Gets a given role's default maximum velocity. This is set by user interface.
Parameters
role Role's index.
Returns
This role's default maximum velocity.
Definition at line 112 of file robots.cpp.
References check_index, default_vel, and get_instance().
Referenced by RobotGUI::create_speeds_frame(), and RobotGUI::update_speed_sliders().
{
     if(!check_index(role)) return 0;
     return get_instance()->default_vel[role];
 }
get_default_velocity()
float Robots::get_default_velocity (int robot) static
Gets a given robot's untouched maximum velocity. This value is not changed by strategy at runtime and can be used as an acceleration base.
Parameters
robot Robot's index.
Returns
This robot's default maximum velocity.
Definition at line 108 of file robots.cpp.
References check_index, default_vel, get_instance(), and list.
Referenced by Strategy::fixed_position_check(), and jsonSaveManager::save_robots().
{
     if(!check_index(robot)) return 0;
     return get_instance()->default_vel[get_instance()->list.at(robot).role];
 }
get_fixedPos()
bool Robots::get_fixedPos (int robot) static
Tells us if a given robot has a fixed position (i.e. strategy's collision check will ignore this one).
Parameters
robot Robot's index.
Returns
True if this robot has a fixed position, False otherwise.
Definition at line 96 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::collision_check(), and Strategy::fixed_position_check().
{
     if(!check_index(robot)) return false;
     return get_instance()->list.at(robot).fixedPos;
 }
get_ID()
char Robots::get_ID (int robot) static
Gets a robot's hardware ID.
Parameters
robot Robot's index.
Returns
A char representing this robot's hardware ID.
Definition at line 72 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by RobotGUI::create_ids_frame(), RobotGUI::event_robots_id_done_bt_signal_clicked(), jsonSaveManager::save_robots(), and RobotGUI::update_ids().
{
     if(!check_index(robot)) return 'N';
     return get_instance()->list.at(robot).ID;
 }
get_instance()
Robots * Robots::get_instance () static private
Returns an existing Robots instance or creates one.
Returns
an instance of robots.
Definition at line 9 of file robots.cpp.
References instance, and Robots().
Referenced by get_cmdType(), get_commands(), get_default_role_velocity(), get_default_velocity(), get_fixedPos(), get_ID(), get_orientation(), get_position(), get_role(), get_secondary_tag(), get_status(), get_target(), get_transAngle(), get_usingPotField(), get_velocity(), is_posistion_set(), is_target_set(), kick(), look_at(), reset_commands(), reset_targets(), set_cmdType(), set_command(), set_default_role_velocity(), set_default_velocity(), set_fixedPos(), set_ID(), set_orientation(), set_position(), set_role(), set_secondary_tag(), set_status(), set_target(), set_transAngle(), set_usingPotField(), set_velocity(), spin_clockwise(), spin_counter_clockwise(), and stop().
{
     if (instance == nullptr) {
         instance = new Robots();
     }
     return instance;
 }
get_orientation()
double Robots::get_orientation (int robot) static
Gets a given robot's orientation.
Parameters
robot Robot's index.
Returns
A double precision decimal value representing it's orientation.
Definition at line 88 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::has_ball(), VSSS_GUI::V4LInterface::updateRobotLabels(), and CamCap::updating_formation().
{
     if(!check_index(robot)) return 0;
     return get_instance()->list.at(robot).orientation;
 }
get_position()
cv::Point Robots::get_position (int robot) static
Gets a given robot's position.
Parameters
robot Robot's index.
Returns
A point representing its position on the screen. Remember: Y grows down, not up.
Definition at line 80 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::atk_routine(), CamCap::capture_and_show(), Strategy::collision_check(), Strategy::def_routine(), Strategy::def_wait(), Strategy::fixed_position_check(), Strategy::get_past(), Strategy::gk_routine(), Strategy::has_ball(), Strategy::is_near(), CamCap::PID_test(), Strategy::position_to_vector(), Strategy::pot_field_around(), Strategy::pot_rotation_decision(), Strategy::potField(), Strategy::set_roles(), VSSS_GUI::V4LInterface::updateRobotLabels(), and CamCap::updating_formation().
{
     if(!check_index(robot)) return cv::Point(-1, -1);
     return get_instance()->list.at(robot).position;
 }
get_role()
int Robots::get_role (int robot) static
Gets a given robot's role. The returned value is managed by strategy.
Parameters
robot Robot's index.
Returns
An int representing this robot's role.
Definition at line 116 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::collision_check(), RobotGUI::create_functions_frame(), jsonSaveManager::save_robots(), Strategy::set_roles(), RobotGUI::update_robot_functions(), and RobotGUI::update_speed_progressBars().
{
     if(!check_index(robot)) return 0;
     return get_instance()->list.at(robot).role;
 }
get_secondary_tag()
cv::Point Robots::get_secondary_tag (int robot) static
Gets the secondary tag position (it's front point) of a given robot.
Parameters
robot Robot's index.
Returns
A point representing robot's front position. Remember: Y grows down, not up.
Definition at line 92 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by CamCap::capture_and_show().
{
     if(!check_index(robot)) return cv::Point(-1, -1);
     return get_instance()->list.at(robot).secondary;
 }
get_status()
int Robots::get_status (int robot) static
Gets a given robot's status. The returned value is managed by strategy.
Parameters
robot Robot's index.
Returns
An int representing this robot's status.
Definition at line 120 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::atk_routine(), Strategy::collision_check(), Strategy::def_routine(), and Strategy::gk_routine().
{
     if(!check_index(robot)) return 0;
     return get_instance()->list.at(robot).status;
 }
get_target()
cv::Point Robots::get_target (int robot) static
Gets a given robot's target.
Parameters
robot Robot's index.
Returns
A point representing its target on the screen. Remember: Y grows down, not up.
Definition at line 84 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by CamCap::capture_and_show(), Strategy::collision_check(), Strategy::crop_targets(), Strategy::def_wait(), Strategy::fixed_position_check(), Strategy::gk_routine(), CamCap::PID_test(), and Strategy::position_to_vector().
{
     if(!check_index(robot)) return cv::Point(-1, -1);
     return get_instance()->list.at(robot).target;
 }
get_transAngle()
double Robots::get_transAngle (int robot) static
Gets a given robot's transposed vector angle. Considering this robot's position and orientation as reference, this value represents the direction this robot must follow.
Parameters
robot Robot's index
Returns
A double-precision decimal value representing this robot's transposed vector angle.
Definition at line 124 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by CamCap::capture_and_show(), Strategy::collision_check(), and Strategy::get_past().
{
     if(!check_index(robot)) return 0;
     return get_instance()->list.at(robot).transAngle;
 }
get_usingPotField()
bool Robots::get_usingPotField (int robot) static
Tells us if a given robot is using potential field.
Parameters
robot Robot's index.
Returns
True if it is using potential field, False otherwise.
Definition at line 76 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::get_targets().
{
     if(!check_index(robot)) return false;
     return get_instance()->list.at(robot).usingPotField;
 }
get_velocity()
float Robots::get_velocity (int robot) static
Gets a given robot's (dynamically set) maximum velocity. This value may be changed by strategy at runtime.
Parameters
robot Robot's index.
Returns
This robot's current maximum velocity.
Definition at line 104 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::fixed_position_check(), and RobotGUI::update_speed_progressBars().
{
     if(!check_index(robot)) return 0;
     return get_instance()->list.at(robot).vmax;
 }
is_posistion_set()
bool Robots::is_posistion_set (int robot) static
Checks if a given robot's position is set. Note: the default unset position is (-1, -1).
Parameters
robot Robot's index.
Returns
True if this robot's position is set, False otherwise.
Definition at line 228 of file robots.cpp.
References check_index, get_instance(), and list.
{
     if(!check_index(robot)) return false;
     return get_instance()->list.at(robot).position.x != -1 && get_instance()->list.at(robot).position.y != -1;
 }
is_target_set()
bool Robots::is_target_set (int robot) static
Checks if a given robot's target position is set. Note: the default unset position is (-1, -1).
Parameters
robot Robot's index.
Returns
True if this robot's target position is set, False otherwise.
Definition at line 232 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by CamCap::capture_and_show(), and CamCap::PID_test().
{
     if(!check_index(robot)) return false;
     return get_instance()->list.at(robot).target.x != -1 && get_instance()->list.at(robot).target.y != -1;
 }
kick()
void Robots::kick (int robot, cv::Point target) static
Goes at maximum velocity to a given target using CMD::VECTOR.
Parameters
robot Robot's index.
target The robot's kick target.
Definition at line 276 of file robots.cpp.
References check_index, get_instance(), list, MAX_VEL, set_target(), and VECTOR.
Referenced by Strategy::atk_routine(), and Strategy::def_routine().
{
     if(!check_index(robot)) return;
     cv::Point pos = get_instance()->list.at(robot).position;
     set_target(robot, target);
     get_instance()->list.at(robot).cmdType = CMD::VECTOR;
     // !TODO verificar a necessidade do último cast pra double
     get_instance()->list.at(robot).transAngle = double(-atan2(double(target.y - pos.y), double(target.x - pos.x)));
     get_instance()->list.at(robot).vmax = MAX_VEL;
 }
look_at() [1/2]
void Robots::look_at (int robot, double orientation, float vel = -1) static
Sends a CMD::ORIENTATION command to turn to a given orientation.
Parameters
robot Robot's index.
orientation The robot's target orientation.
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 259 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and ORIENTATION.
Referenced by Strategy::def_wait(), Strategy::gk_routine(), and CamCap::updating_formation().
{
     if(!check_index(robot)) return;
     if(vel == -1) vel = get_instance()->default_vel[get_instance()->list.at(robot).role];
     get_instance()->list.at(robot).cmdType = CMD::ORIENTATION;
     get_instance()->list.at(robot).targetOrientation = orientation;
     get_instance()->list.at(robot).vmax = vel;
 }
look_at() [2/2]
void Robots::look_at (int robot, cv::Point target, float vel = -1) static
Sends a CMD::ORIENTATION command to face a given point.
Parameters
robot Robot's index.
target The point that this robot must turn to.
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 266 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and ORIENTATION.
{
     if(!check_index(robot)) return;
     if(vel == -1) vel = get_instance()->default_vel[get_instance()->list.at(robot).role];
     // !TODO verificar a necessidade do último cast pra double
     double orientation = double(atan2(double(target.y - get_instance()->list.at(robot).position.y), -double(target.x - get_instance()->list.at(robot).position.x)));
     get_instance()->list.at(robot).cmdType = CMD::ORIENTATION;
     get_instance()->list.at(robot).targetOrientation = orientation;
     get_instance()->list.at(robot).vmax = vel;
 }
reset_commands()
void Robots::reset_commands () static
Resets all robots' velocities, targets and sets command types to CMD::VECTOR.
Definition at line 219 of file robots.cpp.
References default_vel, get_instance(), list, and VECTOR.
Referenced by CamCap::capture_and_show().
{
     for(Robot & r : get_instance()->list) {
         r.cmdType = CMD::VECTOR;
         r.target = cv::Point(-1, -1);
         r.Vl = r.Vr = 0;
         r.vmax = get_instance()->default_vel[r.role];
     }
 }
reset_targets()
void Robots::reset_targets () static
Resets all robots' CMD::POSITION target positions by setting them to (-1, -1).
Definition at line 214 of file robots.cpp.
References get_instance(), and list.
Referenced by CamCap::capture_and_show().
{
     for(Robot & r : get_instance()->list) {
         r.target = cv::Point(-1, -1);
     }
 }
set_cmdType()
void Robots::set_cmdType (int robot, CMD cmdType) static
Sets a given robot's command type.
Parameters
robot Robot's index.
cmdType An enum CMD value representing the new command type.
Definition at line 145 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::atk_routine(), Strategy::def_routine(), Strategy::gk_routine(), and Strategy::reset_flags().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).cmdType = cmdType;
 }
set_command() [1/3]
void Robots::set_command (int robot, cv::Point target, float vel = -1) static
Sets a given robot's CMD::POSITION command. This changes it's command type, target position and maximum velocity.
Parameters
robot Robot's index.
target The new robot's target position.
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 193 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and POSITION.
Referenced by Strategy::collision_check(), CamCap::PID_test(), and CamCap::updating_formation().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).cmdType = CMD::POSITION;
     get_instance()->list.at(robot).target = target;
     if(vel == -1) get_instance()->list.at(robot).vmax = get_instance()->default_vel[get_instance()->list.at(robot).role];
     else get_instance()->list.at(robot).vmax = vel;
 }
set_command() [2/3]
void Robots::set_command (int robot, float Vl, float Vr) static
Sets a given robot's CMD::SPEED command. This changes it's command type, general maximum velocity and each wheel's maximum velocity. This is the robot's most primitive command.
Parameters
robot Robot's index.
Vl New maximum left wheel velocity.
Vr New maximum right wheel velocity.
Definition at line 200 of file robots.cpp.
References check_index, get_instance(), list, and SPEED.
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).cmdType = CMD::SPEED;
     get_instance()->list.at(robot).Vl = Vl;
     get_instance()->list.at(robot).Vr = Vr;
 }
set_command() [3/3]
void Robots::set_command (int robot, double theta, float vel = -1) static
Sets a given robot's CMD::VECTOR command. This changes it's command type, transposed target vector angle and maximum velocity.
Parameters
robot Robot's index.
theta The new robot's transposed target vector angle. (This should not be used to send CMD::ORIENTATION commands. For this, use look_at() method.)
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 206 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and VECTOR.
                                                            { // vector - comando de orientação é o look_at
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).cmdType = CMD::VECTOR;
     get_instance()->list.at(robot).transAngle = theta;
     if(vel == -1) get_instance()->list.at(robot).vmax = get_instance()->default_vel[get_instance()->list.at(robot).role];
     else get_instance()->list.at(robot).vmax = vel;
 }
set_default_role_velocity()
void Robots::set_default_role_velocity (int role, float vel) static
Sets a given role's default velocity.
Parameters
role Role's index.
vel The role's new default velocity.
Definition at line 173 of file robots.cpp.
References check_index, default_vel, and get_instance().
Referenced by RobotGUI::event_robots_speed_done_bt_signal_clicked().
{
     if(!check_index(role)) return;
     get_instance()->default_vel[role] = vel;
 }
set_default_velocity()
void Robots::set_default_velocity (int robot, float vel) static
Sets a given robot's role a new default velocity.
Parameters
robot Robot's index.
vel The role's new default velocity.
Definition at line 169 of file robots.cpp.
References check_index, default_vel, get_instance(), and list.
Referenced by jsonSaveManager::load_robots().
{
     if(!check_index(robot)) return;
     get_instance()->default_vel[get_instance()->list.at(robot).role] = vel;
 }
set_fixedPos()
void Robots::set_fixedPos (int robot, bool fixedPos) static
Sets a given robot's fixed position status.
Parameters
robot Robot's index.
fixedPos Is this robot's position fixed?.
Definition at line 149 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::def_wait(), Strategy::gk_routine(), Strategy::reset_flags(), and CamCap::updating_formation().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).fixedPos = fixedPos;
 }
set_ID()
void Robots::set_ID (int robot, char ID) static
SETTERS.
Sets a given robot's hardware ID.
Parameters
robot Robot's index.
ID The new ID to be set.
Definition at line 129 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by RobotGUI::event_robots_id_done_bt_signal_clicked(), and jsonSaveManager::load_robots().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).ID = ID;
 }
set_orientation()
void Robots::set_orientation (int robot, double orientation) static
Sets a given robot's orientation.
Parameters
robot Robot's index.
orientation A double-precision decimal number representing the robot's new orientation.
Definition at line 137 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Vision::pick_a_tag().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).orientation = orientation;
 }
set_position()
void Robots::set_position (int robot, cv::Point position) static
Sets a given robot's position.
Parameters
robot Robot's index.
position A point representing the new robot's position.
Definition at line 133 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Vision::pick_a_tag().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).position = position;
 }
set_role()
void Robots::set_role (int robot, int role) static
Sets a given robot's role. This value is managed by strategy.
Parameters
robot Robot's index.
role The new robot's role.
Definition at line 181 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by RobotGUI::event_robots_function_done_bt_signal_clicked(), jsonSaveManager::load_robots(), and Strategy::set_role().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).role = role;
 }
set_secondary_tag()
void Robots::set_secondary_tag (int robot, cv::Point secondary) static
Sets a given robot's secondary tag (robot's front point).
Parameters
robot Robot's index.
secondary A point representing it's new secondary point.
Definition at line 141 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Vision::pick_a_tag().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).secondary = secondary;
 }
set_status()
void Robots::set_status (int robot, int status) static
Sets a given robot's status. This value is managed by strategy.
Parameters
robot Robot's index.
status The new robot's status.
Definition at line 177 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::atk_routine(), Strategy::def_routine(), and Strategy::set_role().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).status = status;
 }
set_target()
void Robots::set_target (int robot, cv::Point target) static
Sets a given robot's target position.
Parameters
robot Robot's index.
target The new robot's target position.
Definition at line 189 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::atk_routine(), Strategy::collision_check(), Strategy::crop_targets(), Strategy::def_routine(), Strategy::gk_routine(), kick(), CamCap::PID_test(), and Strategy::pot_field_around().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).target = target;
 }
set_transAngle()
void Robots::set_transAngle (int robot, double transAngle) static
Sets a given robot's transposed vector angle. Considering this robot's position and orientation as reference, this value represents the direction this robot must follow.
Parameters
robot Robot's index.
transAngle The new robot's transposed vector angle.
Definition at line 185 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::collision_check(), Strategy::position_to_vector(), and Strategy::pot_field_around().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).transAngle = transAngle;
 }
set_usingPotField()
void Robots::set_usingPotField (int robot, bool usingPotField) static
Sets a given robot's 'using potential field' status.
Parameters
robot Robot's index.
usingPotField Is this robot's using potential field?.
Definition at line 153 of file robots.cpp.
References check_index, get_instance(), and list.
Referenced by Strategy::pot_field_around(), Strategy::potField(), and Strategy::reset_flags().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).usingPotField = usingPotField;
 }
set_velocity() [1/3]
void Robots::set_velocity (int robot, int role) static
Sets a given robot's maximum velocity to a given role's default.
Parameters
robot Robot's index.
role A role that will be the reference to the robot's velocity.
Definition at line 157 of file robots.cpp.
References check_index, default_vel, get_instance(), and list.
Referenced by Strategy::atk_routine(), Strategy::def_routine(), Strategy::fixed_position_check(), Strategy::gk_routine(), and Strategy::set_role().
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).vmax = get_instance()->default_vel[role];
 }
set_velocity() [2/3]
void Robots::set_velocity (int robot, float velocity) static
Sets a given robot's maximum velocity to a given value.
Parameters
robot Robot's index.
velocity The robot's new velocity.
Definition at line 161 of file robots.cpp.
References check_index, get_instance(), and list.
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).vmax = velocity;
 }
set_velocity() [3/3]
void Robots::set_velocity (int robot) static
Resets a given robot's velocity to it's role's default.
Parameters
robot Robot's index.
Definition at line 165 of file robots.cpp.
References check_index, default_vel, get_instance(), and list.
{
     if(!check_index(robot)) return;
     get_instance()->list.at(robot).vmax = get_instance()->default_vel[get_instance()->list.at(robot).role];
 }
spin_clockwise()
void Robots::spin_clockwise (int robot, float vel = -1) static
Commands a robot to spin clockwiselly. To do this, it sends a CMD::SPEED with Vl = vel and Vr = -vel.
Parameters
robot Robot's index.
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 246 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and SPEED.
Referenced by Strategy::atk_routine(), Strategy::def_routine(), Strategy::gk_routine(), and spin_counter_clockwise().
{
     if(!check_index(robot)) return;
     if(vel == -1) vel = get_instance()->default_vel[get_instance()->list.at(robot).role];
     get_instance()->list.at(robot).cmdType = CMD::SPEED;
     get_instance()->list.at(robot).vmax = abs(vel);
     get_instance()->list.at(robot).Vr = -vel;
     get_instance()->list.at(robot).Vl = vel;
 }
spin_counter_clockwise()
void Robots::spin_counter_clockwise (int robot, float vel = -1) static
Commands a robot to spin counter-clockwiselly. To do this, it calls spin_counter_clockwise(robot, -vel).
Parameters
robot Robot's index.
vel (optional) Robot's velocity while executing this command. (If not specified, the default maximum velocity for it's role is used.)
Definition at line 254 of file robots.cpp.
References check_index, default_vel, get_instance(), list, and spin_clockwise().
Referenced by Strategy::atk_routine(), Strategy::def_routine(), and Strategy::gk_routine().
{
     if(!check_index(robot)) return;
     if(vel == -1) vel = get_instance()->default_vel[get_instance()->list.at(robot).role];
     spin_clockwise(robot, -vel);
 }
stop()
void Robots::stop (int robot) static
Stops a robot by sending a CMD::SPEED where Vl = Vr = 0, resetting target position and setting maximum velocity to 0.
Parameters
robot Robot's index.
Definition at line 236 of file robots.cpp.
References check_index, get_instance(), list, and SPEED.
Referenced by Strategy::fixed_position_check(), and CamCap::PID_test().
{
     if(!check_index(robot)) return;
     // pode fazer de duas formas: mandando ele ir pra própria posição ou setando 0 nas rodas
     // get_instance()->list.at(robot).target = get_instance()->list.at(robot).position;
     get_instance()->list.at(robot).cmdType = CMD::SPEED;
     get_instance()->list.at(robot).vmax = 0;
     get_instance()->list.at(robot).Vr = 0;
     get_instance()->list.at(robot).Vl = 0;
     get_instance()->list.at(robot).target = cv::Point(-1, -1);
 }
Field Documentation
default_vel
float Robots::default_vel[3] private
The default velocities for each role (GK, DEF or ATK)
Definition at line 156 of file robots.hpp.
Referenced by get_default_role_velocity(), get_default_velocity(), look_at(), reset_commands(), Robots(), set_command(), set_default_role_velocity(), set_default_velocity(), set_velocity(), spin_clockwise(), and spin_counter_clockwise().
instance
Robots * Robots::instance = nullptr static private
The unique instance of this class.
Definition at line 159 of file robots.hpp.
Referenced by get_instance().
list
std::vector<Robot> Robots::list private
A list of N robots. Must be unique in the entire program.
Definition at line 153 of file robots.hpp.
Referenced by get_cmdType(), get_commands(), get_default_velocity(), get_fixedPos(), get_ID(), get_orientation(), get_position(), get_role(), get_secondary_tag(), get_status(), get_target(), get_transAngle(), get_usingPotField(), get_velocity(), is_posistion_set(), is_target_set(), kick(), look_at(), reset_commands(), reset_targets(), Robots(), set_cmdType(), set_command(), set_default_velocity(), set_fixedPos(), set_ID(), set_orientation(), set_position(), set_role(), set_secondary_tag(), set_status(), set_target(), set_transAngle(), set_usingPotField(), set_velocity(), spin_clockwise(), spin_counter_clockwise(), and stop().
MAX_VEL
constexpr float Robots::MAX_VEL = 1.4f static
Robot's physical maximum velocity in meters/second. Can be used by all classes statically or dynamically.
Definition at line 24 of file robots.hpp.
Referenced by kick().
SIZE
const int Robots::SIZE = 3 static
The number of robots. Can be used by all classes statically or dynamically.
Definition at line 21 of file robots.hpp.
Referenced by CamCap::capture_and_show(), RobotGUI::create_functions_frame(), RobotGUI::create_ids_frame(), RobotGUI::create_speeds_frame(), RobotGUI::event_robots_function_done_bt_signal_clicked(), RobotGUI::event_robots_function_edit_bt_signal_clicked(), RobotGUI::event_robots_id_done_bt_signal_clicked(), RobotGUI::event_robots_id_edit_bt_signal_pressed(), RobotGUI::event_robots_speed_done_bt_signal_clicked(), RobotGUI::event_robots_speed_edit_bt_signal_pressed(), jsonSaveManager::load_robots(), CamCap::PID_test(), Strategy::reset_flags(), jsonSaveManager::save_robots(), Strategy::set_roles(), RobotGUI::update_ids(), RobotGUI::update_robot_functions(), RobotGUI::update_speed_progressBars(), RobotGUI::update_speed_sliders(), CamCap::updateAllPositions(), and CamCap::updating_formation().
The documentation for this class was generated from the following files:
src/robots.hpp
src/robots.cpp